### ISSUE TITLE
Añadir arte al proyecto en la carpeta de "art"

### ISSUE THREAD

**Issue by AARCOF** [AARCOF/Play-To-Fail-Juego-en-Godot#1]
Se requiere el arte para continuar el desarrollo de los niveles.
@Aronsine debe añadir las bases en formato .jpg o .png a la carpeta "art".

**Comment by AronOmarPizarroCahuana** [comment]
Ya se añadió la carpeta con algunos estilos e imágenes .jpg y .png para el desarrollo.
