### ISSUE TITLE
Error en función ["func touch_difference()"]

### ISSUE THREAD

**Issue by AARCOF** [AARCOF/Play-To-Fail-Juego-en-Godot#2]
Los valores no ingresan a la función y no se ejecuta de manera correcta, es decir, no hace el cambio de pixeles.
Línea 98.
@Lionnos @k4lFer

**Comment by k4lFer** [comment]
**Solucionado.**
Error encontrado en la codificación de la función _"func swap_pieces()"_.
Commit arreglado y subido a la rama _**fix_develop**_
